services:
  web:
    container_name: 2026-1-RetinaScan-Web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
