services:
  2026-1-retinascan-web-homolog:
    container_name: 2026-1-RetinaScan-Web-Homolog
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    networks:
      - web
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.retinascan-web-homolog.rule=Host(`homolog.retinascan.site`)"
      - "traefik.http.routers.retinascan-web-homolog.entrypoints=websecure"
      - "traefik.http.routers.retinascan-web-homolog.tls=true"
      - "traefik.http.routers.retinascan-web-homolog.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.retinascan-web-homolog.service=retinascan-web-homolog-svc"
      - "traefik.http.services.retinascan-web-homolog-svc.loadbalancer.server.port=3001"

networks:
  web:
    external: true
    name: web