# para executar:
# python -m pytest -s test/seleniumIDE/test_retinaScanlogin.py -k test_retinaScanlogin

# Generated by Selenium IDE
import json
import time

import pytest

from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestRetinaScanlogin:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_retinaScanlogin(self):
        self.driver.get("https://retinascan.site/login")
        self.driver.set_window_size(959, 728)
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(1) .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(1) .h-8").send_keys("admin@retinascan.local")
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(2) .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(2) .h-8").send_keys("admin-retina")
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".group\\/button").click()
        time.sleep(3)
        self.driver.find_element(By.LINK_TEXT, "Controle de usuários").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".bg-primary").click()
        time.sleep(3)
        element = self.driver.find_element(By.CSS_SELECTOR, ".bg-primary")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element_with_offset(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-4 > .space-y-2:nth-child(1) > .h-8").send_keys("Francisco")
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-4 > .space-y-2:nth-child(2) > .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-4 > .space-y-2:nth-child(2) > .h-8").send_keys(
            "chico@gmail.com"
        )
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(3) > .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(3) > .h-8").send_keys("1996-04-23")
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(4) > .space-y-2:nth-child(1) > .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(4) > .space-y-2:nth-child(1) > .h-8").send_keys(
            "777.999.444-22"
        )
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(4) > .space-y-2:nth-child(2) > .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(4) > .space-y-2:nth-child(2) > .h-8").send_keys(
            "011111/SP"
        )
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) > .space-y-2:nth-child(1) > .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) > .space-y-2:nth-child(1) > .h-8").send_keys(
            "123456"
        )
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) > .space-y-2:nth-child(2) > .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) > .space-y-2:nth-child(2) > .h-8").send_keys(
            "123456"
        )
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".-mx-4 > .group\\/button:nth-child(2)").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(4) > .space-y-2:nth-child(1) > .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".-mx-4").click()
        self.driver.find_element(By.CSS_SELECTOR, ".bg-secondary").click()
        self.driver.find_element(By.LINK_TEXT, "Exames").click()
        time.sleep(3)
        self.driver.find_element(By.LINK_TEXT, "Novo exame").click()
        time.sleep(3)
        self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
        self.driver.find_element(By.CSS_SELECTOR, ".truncate:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".group\\/button").click()
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(1) .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(1) .h-8").send_keys("chico@gmail.com")
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(2) .h-8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".space-y-2:nth-child(2) .h-8").send_keys("123")
        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".group\\/button").click()

        time.sleep(3)
        self.driver.find_element(By.CSS_SELECTOR, ".group\\/button").click()
