name: Deploy

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
    types: [closed]

permissions:
  deployments: write
  contents: read

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment:
      name: homolog
      url: https://homolog.retinascan.site/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute Docker Compose on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd homolog/2026-1-RetinaScan-Web/
            git pull origin develop
            docker compose -f docker-compose.homolog.yml up -d --build
            docker image prune -f
