name: Export de métricas

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    if: >
      github.event_name == 'push' || 
      (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'NOT RELEASE') == false)
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests python-dotenv packaging pandas

      - name: Criar diretório
        run: mkdir -p analytics-raw-data

      - name: Coletar métricas no SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          REPO: ${{ github.event.repository.name }}
          REPO_DOC: '2026-1-RetinaScan-Doc'
          RELEASE_MAJOR: ${{ contains(github.event.pull_request.labels.*.name, 'MAJOR RELEASE') }}
          RELEASE_MINOR: ${{ contains(github.event.pull_request.labels.*.name, 'MINOR RELEASE') }}
          RELEASE_FIX: ${{ contains(github.event.pull_request.labels.*.name, 'FIX RELEASE') }}
        run: python ./sonar_scripts/parser.py

      - name: Envia métricas para repo de Doc
        run: |
          git config --global user.email "${{secrets.USER_EMAIL}}"
          git config --global user.name "${{secrets.USER_NAME}}"
          git clone --single-branch --branch main "https://x-access-token:${{secrets.API_TOKEN_GITHUB}}@github.com/fga-eps-mds/2026-1-RetinaScan-Doc" doc
          mkdir -p doc/analytics-raw-data
          cp -R analytics-raw-data/*.json doc/analytics-raw-data
          cd doc
          git add .
          git commit -m "Adicionando métricas do repositório ${{ github.event.repository.name }} ${{ github.ref_name }}" || echo "Sem alterações"
          git push

      - name: Envia métricas como assets da release
        if: startsWith(github.ref, 'refs/tags')
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'analytics-raw-data/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
